# Site settings
title: Thorp's Profile
email: thorp@landofflorp.ho
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: "/patchwork-gh-pages"
url: "http://gkassee.github.io"


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
